# PACKAGES
## Install packages

In [1]:
!pip install panda
!pip install numpy
!pip install scipy
!pip install sklearn

  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7263 sha256=a6968daa5cbdcd6f29767be6bc04db9e16a3f46dc66b66e52ce9dc4ef5201388
  Stored in directory: c:\users\lythe\appdata\local\pip\cache\wheels\e6\3d\81\a3665ce657d35359ca337b1db2975dbe5cd281a88b8982f6b6
Successfully built panda
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=47fe2d45462824bde0334229b0f8b344fc3d16bfc1e7496f2f4d3ec6dcd461ff
  Stored in directory: c:\users\lythe\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


## Import packages

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

'''
It features various classification, regression and clustering algorithms including support
vector machines, random forests, gradient boosting, k-means and DBSCAN, and is designed to
interoperate with the Python numerical and scientific libraries NumPy and SciPy
'''

# DATA
## Load data

In [3]:
data = pd.read_csv('data/b5.csv')

In [4]:
data

E1  E2  E3  E4  E5  E6  E7  E8  E9  E10  ...  O1  O2  O3  O4  O5  O6  \
0       4   2   5   2   5   1   4   3   5    1  ...   4   1   3   1   5   1   
1       2   2   3   3   3   3   1   5   1    5  ...   3   3   3   3   2   3   
2       5   1   1   4   5   1   1   5   5    1  ...   4   5   5   1   5   1   
3       2   5   2   4   3   4   3   4   4    5  ...   4   3   5   2   4   2   
4       3   1   3   3   3   1   3   1   3    5  ...   3   1   1   1   3   1   
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ..  ..  ..  ..  ..  ..   
18925   1   4   3   5   4   3   1   2   1    5  ...   1   3   5   3   4   1   
18926   2   3   2   3   2   3   2   4   4    4  ...   1   2   3   2   3   3   
18927   2   5   4   5   5   5   1   2   1    5  ...   5   3   1   3   4   1   
18928   1   4   2   3   2   4   1   3   4    5  ...   3   2   5   3   4   1   
18929   2   3   1   5   3   3   3   2   2    4  ...   5   1   5   1   4   1   

       O7  O8  O9  O10  
0       4   2   5    5  
1       3   1   3    2  
2       5   5   5    5  
3       5   2   5    5  
4       3   1   5    3  
...    ..  ..  ..  ...  
18925   4   2   5    3  
18926   4   2   3    3  
18927   1   5   5    5  
18928   5   3   5    5  
18929   5   5   5    5  

[18930 rows x 50 columns]

### Convert data to NumPy array

In [6]:
# TODO: assign data to new variable
x = data.values

### Scale the values

In [7]:
X = scale(x)
'''
To make all variables on the same range
'''

In [10]:
x

array([[4, 2, 5, ..., 2, 5, 5],
       [2, 2, 3, ..., 1, 3, 2],
       [5, 1, 1, ..., 5, 5, 5],
       ...,
       [2, 5, 4, ..., 5, 5, 5],
       [1, 4, 2, ..., 3, 5, 5],
       [2, 3, 1, ..., 5, 5, 5]], dtype=int64)

In [9]:
X

array([[ 1.112632  , -0.57855181,  1.28086553, ..., -0.96448433,
         0.88177594,  1.0099427 ],
       [-0.51209309, -0.57855181, -0.33817724, ..., -1.76030372,
        -1.15794039, -2.03840414],
       [ 1.92499454, -1.34069418, -1.95722   , ...,  1.42297383,
         0.88177594,  1.0099427 ],
       ...,
       [-0.51209309,  1.70787529,  0.47134415, ...,  1.42297383,
         0.88177594,  1.0099427 ],
       [-1.32445564,  0.94573292, -1.14769862, ..., -0.16866494,
         0.88177594,  1.0099427 ],
       [-0.51209309,  0.18359055, -1.95722   , ...,  1.42297383,
         0.88177594,  1.0099427 ]])

## ANALYSIS
### PCA with 50 components

In [8]:
# TODO: Principal component analysis
pca = PCA()
'''
Linear dimensionality reduction using Singular 
Value Decomposition of the data to project it to a lower dimensional space
'''
pca.fit(x)
print(pca.explained_variance_ratio_)
'''
explain the variance
'''

[0.1732156  0.10143879 0.07428057 0.0594228  0.05669894 0.03133458
 0.02613953 0.02158968 0.02038172 0.01949732 0.01834806 0.01771354
 0.01667488 0.01609622 0.01522287 0.01431982 0.01378619 0.01371048
 0.01308668 0.01276898 0.01245795 0.0119073  0.01164292 0.01146333
 0.01123541 0.01108724 0.0107055  0.0103613  0.01010978 0.00989842
 0.00966316 0.00932905 0.00924089 0.00906615 0.00898054 0.00892901
 0.00882098 0.00857636 0.00831302 0.00812122 0.00802491 0.00787273
 0.00758522 0.00670902 0.00655309 0.00639817 0.00611336 0.00546774
 0.00519423 0.00444478]


In [11]:
pca.fit(x)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

## PCA with 5 components

In [12]:
pca5 = PCA(n_components=5)
'''
In here, n_components = 5 means of 5 components solution, which is assumed by developer
'''
pca5.fit(x)
print(pca5.explained_variance_ratio_)
'''
print out the explaination of variances
'''

[0.1732156  0.10143879 0.07428055 0.0594226  0.05669874]


## Contributions of variables to components

In [13]:
print(pca5.components_)

[[-1.87185095e-01  1.95213887e-01 -2.52862669e-01  2.11893083e-01
  -2.40797111e-01  1.95787615e-01 -2.63457342e-01  1.44216834e-01
  -1.92919407e-01  2.23369792e-01  1.79006366e-01 -1.29476144e-01
   1.27828229e-01 -1.09219219e-01  1.54854274e-01  1.94564965e-01
   1.85859570e-01  2.05901807e-01  1.97840768e-01  2.22842607e-01
   9.12167552e-02 -1.40214082e-01  9.03999750e-02 -7.59434143e-02
   1.05809358e-01 -3.33468764e-02  1.57713745e-01 -9.40223203e-02
  -8.29721745e-02 -1.47219740e-01 -9.09625394e-02  6.07955661e-02
  -4.61242113e-02  1.56144376e-01 -1.07330580e-01  1.10005395e-01
  -3.44705673e-02  1.22281914e-01 -8.56697311e-02 -6.50917202e-02
  -4.95033402e-02  7.93529370e-02 -1.32455158e-02  5.18879990e-02
  -8.41235953e-02  6.10032015e-02 -7.02537864e-02  3.11209319e-04
   1.82674353e-02 -7.56870466e-02]
 [-1.78897904e-01  2.27283883e-01 -1.07463658e-01  1.49473847e-01
  -1.94886185e-01  1.60118082e-01 -2.17635203e-01  1.67688468e-01
  -1.97486436e-01  1.37153372e-01 -2.0668